---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - 'App Store'
  - Calendar
  - Contacts
  - FaceTime
  - Home
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Photos
  - Podcasts
  - Reminders
  - Safari
  - Stickies
  - Stocks
  - 'System Preferences'
  - TextEdit
  - TV
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 1
  - name: "Microsoft Outlook"
    path: "/Applications/Microsoft Outlook.app/"
    pos: 2
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 3
  - name: "Microsoft Teams"
    path: "/Applications/Microsoft Teams.app/"
    pos: 4
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 5
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 6
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 7
  - name: "GIMP-2.10"
    path: "/Applications/GIMP-2.10.app/"
    pos: 8
  - name: "Microsoft OneNote"
    path: "/Applications/Microsoft OneNote.app/"
    pos: 9
  - name: "Microsoft Remote Desktop"
    path: "/Applications/Microsoft Remote Desktop.app/"
    pos: 10
  - name: "MongoDB Compass"
    path: "/Applications/MongoDB Compass.app/"
    pos: 11

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/flamableconcrete/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .gitignore
  - .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - certbot
  - cowsay
  - direnv
  - docker-compose
  - git
  - git-extras
  - gpg
  - graphviz
  - htop
  - imagemagick
  - jq
  - nvm
  - openssl
  - packer
  - postgresql
  - p7zip
  - pv
  - pyenv
  - readline  # pyenv
  - sqlite3  # pyenv
  - ssh-copy-id
  - starship
  - tcl-tk  # pyenv
  - tmux
  - tree
  - wget
  - xz  # pyenv
  - zlib  # pyenv

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - chromedriver
  - discord
  - docker
  - font-fira-code-nerd-font
  - gimp
  - google-chrome
  - hiddenbar
  - iterm2
  - itsycal
  - licecap  # quickly create gifs
  - microsoft-remote-desktop
  - rectangle
  - slack
  - sublime-text
  - vagrant
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

git_repos:
  - url: "https://github.com/flamableconcrete/mac-dev-playbook.git"
    path: "/Users/{{ ansible_env.USER }}/code/github/flamableconcrete/mac-dev-playbook"
  - url: "https://github.com/flamableconcrete/dotfiles.git"
    path: "/Users/{{ ansible_env.USER }}/code/github/flamableconcrete/dotfiles"
  - url: "https://github.com/zsh-users/zsh-autosuggestions.git"
    path: "/Users/{{ ansible_env.USER }}/.zsh_custom/plugins/zsh-autosuggestions"
  - url: "https://github.com/zsh-users/zsh-completions.git"
    path: "/Users/{{ ansible_env.USER }}/.zsh_custom/plugins/zsh-completions"
  - url: "https://github.com/flamableconcrete/zsh-motd.git"
    path: "/Users/{{ ansible_env.USER }}/.zsh_custom/plugins/zsh-motd"
  - url: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    path: "/Users/{{ ansible_env.USER }}/.zsh_custom/plugins/zsh-syntax-highlighting"
extra_git_repos: []
#  - url: "https://github.com/flamableconcrete/dotfiles.git"
#    path: "/Users/{{ ansible_env.USER }}/code/dotfiles-test"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
